import Head from "next/head";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";

export default function SignUp() {
	const router = useRouter();
	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm();

	const onSubmit = async (data) => {
		if (data.password !== data.rePassword) {
			alert("As senhas não conferem");
			return;
		}

		await sendData(data)
			.then((response) => {
				alert("Registro efetuado com sucesso!");
				router.push("/autenticacao/entrar");
			})
			.catch((error) => {
				alert("Erro ao efetuar o registro!");
			});
	};

	const sendData = async (data) => {
		const response = await fetch("/api/registro-usuario/envia-registro", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify(data),
		});

		return response.json();
	};

	return (
		<div>
			<Head>
				<title>Registrar-se</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="container-fluid m-0">
					<div className="row">
						<div className="bgSignUpDog col-6 col-6 pt-4 ps-5 pe-5 pb-4 fullHeight">
							<Link href="/" passHref>
								<h1 className="customLink">Pet-Lovers</h1>
							</Link>
							<p>+Simplicidade -Burocracia</p>
						</div>
						<div className="col-6 col-6 pt-4 ps-5 pe-5 pb-4 fullHeight">
							<div className="row mt-5">
								<div className="col-12">
									<h1>Aqui tudo é simples, até o registro</h1>
									<small>Bem-vindo ao Pet-lovers</small>
								</div>
							</div>
							<div className="row mt-3">
								<div className="col-12">
									<form
										onSubmit={handleSubmit(onSubmit)}
										className="row g-3"
									>
										<div className="col-12">
											<label
												htmlFor="inputEmail4"
												className="form-label"
											>
												Email
											</label>
											<input
												type="email"
												className="form-control"
												id="inputEmail4"
												defaultValue=""
												{...register("email", {
													required: true,
												})}
											/>
											{errors.email && (
												<span className="text-danger">
													Esse campo é obrigatório
												</span>
											)}
										</div>
										<div className="col-6">
											<label
												htmlFor="inputPassword4"
												className="form-label"
											>
												Senha
											</label>
											<input
												type="password"
												className="form-control"
												id="inputPassword4"
												defaultValue=""
												{...register("password", {
													required: true,
													minLength: 8,
												})}
											/>
											{errors.password && (
												<span className="text-danger">
													Esse campo é obrigatório
												</span>
											)}
										</div>
										<div className="col-6">
											<label
												htmlFor="inputRePassword4"
												className="form-label"
											>
												Repetir a senha
											</label>
											<input
												type="password"
												className="form-control"
												id="inputRePassword4"
												defaultValue=""
												{...register("rePassword", {
													required: true,
													minLength: 8,
												})}
											/>
											{errors.rePassword && (
												<span className="text-danger">
													Esse campo é obrigatório
												</span>
											)}
										</div>
										<div className="col-12">
											<button
												type="submit"
												className="btn btn-info"
											>
												Registrar e Entrar
											</button>
										</div>
									</form>
								</div>
							</div>
							<div className="row mt-3">
								<div className="col-12 text-center">
									já tem uma conta? <br />
									<Link href="/autenticacao/entrar">
										<a href="" className="customLink">
											Entrar
										</a>
									</Link>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
