import Head from "next/head";
import Link from "next/link";
import {
	auth,
	signInWithEmailAndPassword,
	signInWithPopup,
	GoogleAuthProvider,
} from "../../../core/config/firebase/client";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";
import { useState } from "react";
import Offcanvas from "react-bootstrap/Offcanvas";
import Button from "react-bootstrap/Button";

export default function SignIn() {
	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm();
	const router = useRouter();

	const onSubmit = ({ email, password }) => {
		signInWithEmailAndPassword(auth, email, password)
			.then(({ user }) => {
				localStorage.setItem("ci", btoa(user.uid));
				router.push("/adocao");
			})
			.catch((error) => {
				alert(error.message);
				const errorCode = error.code;
				const errorMessage = error.message;
			});
	};

	const signInWithGoogle = () => {
		signInWithPopup(auth, new GoogleAuthProvider())
			.then(({ user }) => {
				router.push("/adocao");
			})
			.catch((error) => {
				const errorCode = error.code;
				const errorMessage = error.message;
			});
	};
	// Offcanvas - Esqueci minha senha
	const [show, setShow] = useState(false);
  	const handleClose = () => setShow(false);
  	const handleShow = () => setShow(true);

	return (
		<div>
			<Head>
				<title>Entrar</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="container-fluid m-0">
					<div className="row">
						<div className="bgSignInDog col-6 col-6 pt-4 ps-5 pe-5 pb-4 fullHeight">
							<Link href="/" passHref>
								<h1 className="customLink">Pet-Lovers</h1>
							</Link>
							<p>
								Simplificando conexões para que você possa achar
								seu pet
							</p>
						</div>
						<div className="col-6 col-6 pt-4 ps-5 pe-5 pb-4 fullHeight">
							<div className="row ms-5 mt-5">
								<div className="col-6 ms-5 ps-5 mb-4">
									<h1>É rápido, É fácil!</h1>
									<small class="ps-1">Bem-vindo de volta</small>
								</div>
							</div>
							<div className="row mt-4 justify-content-center">
								<div className="col-8">
									<div className="d-grid gap-2">
										<button
											className="btn btn-outline-danger"
											type="button"
											onClick={signInWithGoogle}
										>
											<h7 class="text-dark fw-bold">Entrar com Google</h7>
											<i className="ms-2 bi bi-google text-dark"></i>
										</button>
									</div>
								</div>
							</div>
							<div className="row mt-4">
								<div className="col-12">
									<div className="text-center">
										<p class="fw-bold">ou</p>
									</div>
									<form
										onSubmit={handleSubmit(onSubmit)}
										className="row g-3 justify-content-center"
									>
										<div className="col-lg-8">
											<label
												htmlFor="signin-email"
												className="form-label"
											>
												E-mail:
											</label>
											<input
												defaultValue=""
												{...register("email", {
													required: true,
												})}
												type="email"
												className="form-control"
												id="signin-email"
											/>
											{errors.email && (
												<span className="text-danger">
													Esse campo é obrigatório
												</span>
											)}
										</div>
										<div className="col-8">
											<label
												htmlFor="signin-password"
												className="form-label"
											>
												Senha:
											</label>
											<input
												defaultValue=""
												{...register("password", {
													required: true,
												})}
												type="password"
												className="form-control"
												id="signin-password"
											/>
											{errors.password && (
												<span className="text-danger">
													Esse campo é obrigatório
												</span>
											)}
										</div>

										<div className="col-6">
											<div className="row justify-content-center">
												<div className="col-6">
													<div className="form-check">
														<input
															className="form-check-input"
															type="checkbox"
															id="gridCheck"
														/>
														<label
															className="form-check-label customLink text-dark"
															htmlFor="gridCheck"
														>
															Lembrar-me
														</label>
													</div>
												</div>
												<div className="col-6 text-end">
													<a
														href="#sidebar"
														className="customLink text-dark"
													>
														Esqueci minha senha
													</a>
													<>
													<Button variant="primary" onClick={handleShow}>
      												  Launch
      												</Button>

      												<Offcanvas show={show} onHide={handleClose}>
      												  <Offcanvas.Header closeButton>
      												    <Offcanvas.Title>Offcanvas</Offcanvas.Title>
      												  </Offcanvas.Header>
      												  <Offcanvas.Body>
      												    Some text as placeholder. In real life you can have the elements you
      												    have chosen. Like, text, images, lists, etc.
      												  </Offcanvas.Body>
      												</Offcanvas>
													</>
												</div>
											</div>
										</div>
										<div class="row justify-content-center">			
											<div className="d-grid gap-2 col-3 mx-auto mt-5 mb-4">
												<button
													type="submit"
													className="btn btn-info btn-lg"
												>
													Entrar
												</button>
											</div>
										</div>	
									</form>
								</div>
							</div>
							<div className="row mt-3">
								<div className="col-12 text-center">
									Não tem uma conta? <br />
									<Link href="/autenticacao/registrar">
										<a href="" className="customLink">
											Registrar-se
										</a>
									</Link>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
