import Head from "next/head";
import Link from "next/link";
import {
	auth,
	signInWithEmailAndPassword,
	signInWithPopup,
	GoogleAuthProvider,
} from "../../../core/config/firebase/client";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";

export default function SignIn() {
	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm();
	const router = useRouter();

	const onSubmit = ({ email, password }) => {
		signInWithEmailAndPassword(auth, email, password)
			.then(({ user }) => {
				localStorage.setItem("ci", btoa(user.uid));
				router.push("/adocao");
			})
			.catch((error) => {
				alert(error.message);
				const errorCode = error.code;
				const errorMessage = error.message;
			});
	};

	const signInWithGoogle = () => {
		signInWithPopup(auth, new GoogleAuthProvider())
			.then(({ user }) => {
				router.push("/adocao");
			})
			.catch((error) => {
				const errorCode = error.code;
				const errorMessage = error.message;
			});
	};

	return (
		<div>
			<Head>
				<title>Entrar</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="container-fluid m-0">
					<div className="row">
						<div className="bgSignInDog col-6 col-6 pt-4 ps-5 pe-5 pb-4 fullHeight">
							<Link href="/" passHref>
								<h1 className="customLink">Pet-Lovers</h1>
							</Link>
							<p>
								Simplificando conexões para que você possa achar
								seu pet
							</p>
						</div>
						<div className="col-6 col-6 pt-4 ps-5 pe-5 pb-4 fullHeight">
							<div className="row mt-5">
								<div className="col-12">
									<h1>É rápido. É fácil!</h1>
									<small>Bem-vindo de volta</small>
								</div>
							</div>
							<div className="row mt-4">
								<div className="col-12">
									<div className="d-grid gap-2">
										<button
											className="btn btn-light"
											type="button"
											onClick={signInWithGoogle}
										>
											Entrar com Google
											<i className="ms-2 bi bi-google text-danger"></i>
										</button>
										<button
											className="btn btn-danger"
											type="button"
										>
											Entrar com Facebook
											<i className="ms-2 bi bi-facebook text-primary"></i>
										</button>
									</div>
								</div>
							</div>
							<div className="row mt-3">
								<div className="col-12">
									<div className="text-center">
										<p>ou</p>
									</div>
									<form
										onSubmit={handleSubmit(onSubmit)}
										className="row g-3"
									>
										<div className="col-12">
											<label
												htmlFor="signin-email"
												className="form-label"
											>
												E-mail
											</label>
											<input
												defaultValue=""
												{...register("email", {
													required: true,
												})}
												type="email"
												className="form-control"
												id="signin-email"
											/>
											{errors.email && (
												<span className="text-danger">
													Esse campo é obrigatório
												</span>
											)}
										</div>
										<div className="col-12">
											<label
												htmlFor="signin-password"
												className="form-label"
											>
												Senha
											</label>
											<input
												defaultValue=""
												{...register("password", {
													required: true,
												})}
												type="password"
												className="form-control"
												id="signin-password"
											/>
											{errors.password && (
												<span className="text-danger">
													Esse campo é obrigatório
												</span>
											)}
										</div>

										<div className="col-12">
											<div className="row">
												<div className="col-6">
													<div className="form-check">
														<input
															className="form-check-input"
															type="checkbox"
															id="gridCheck"
														/>
														<label
															className="form-check-label text-danger"
															htmlFor="gridCheck"
														>
															Lembrar-me
														</label>
													</div>
												</div>
												<div className="col-6 text-end">
													<a
														href=""
														className="customLink text-danger"
													>
														Esqueci minha senha
													</a>
												</div>
											</div>
										</div>
										<div className="col-12">
											<button
												type="submit"
												className="btn btn-info"
											>
												Entrar
											</button>
										</div>
									</form>
								</div>
							</div>
							<div className="row mt-3">
								<div className="col-12 text-center">
									Não tem uma conta? <br />
									<Link href="/autenticacao/registrar">
										<a href="" className="customLink">
											Registrar-se
										</a>
									</Link>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
